services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./database/.env

  app:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: my_app
    depends_on:
      - db
    ports:
      - "3000:3000"
    #volumes:
     # - .:/app
    env_file:
      - ./api/.env

volumes:
  pg_data:
