version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./datasabe/.env


  api: 
    build: api
    env_file:
      - ./api/.env
    ports:
      - 8081:8080

volumes:
  db-data:
